version: '3.7'

services:
  db:
    image: postgres:15.1
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
        - .env
volumes:
  postgres_data:
    name: clerk-pg-data
